version: '3'
services:
  order_db:
    image: postgres:alpine
    volumes:
      - ./.persistence/order_db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USERNAME: postgres
      POSTGRES_DB: db_order
    ports:
      - 15432:5432
  order:
    build: .
    ports:
      - 9004:9004
    depends_on:
      - order_db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://order_db:5432/db_order
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL-AUTO: update
      SERVER_PORT: 9004
